### ISSUE TITLE
README links to a "proxy" repo but it's a 404

### ISSUE THREAD

**Issue by pdurbin** [datacite/proxy-cookbook#2]
This link in the README is a 404: https://github.com/datacite/proxy

I was trying to help someone figure out if the proxy code is open source or not: http://irclog.iq.harvard.edu/dataverse/2019-03-27#i_89187

**Comment by mfenner** [comment]
@pdurbin this is some old code we haven't used in a while. We switched to AWS application load balancers a while ago. You can find our configuration in this repo: https://github.com/datacite/mastino

But I am not sure that the reverse proxy DataCite uses in Front of AWS Elastic Container Service is what you are looking for,

**Comment by pdurbin** [comment]
@poikilotherm can you please explain what you're looking for?

My understanding is that he's thinking about running a DataCite proxy similar to the one run by Australian National Data Service (ANDS) and was wondering if the code is open source. From the Dataverse perspective, we indicate that https://researchdata.ands.org.au/api/doi/datacite can be used instead of the normal https://mds.datacite.org service. These docs (screenshot below) are here: http://guides.dataverse.org/en/4.11/installation/config.html#doi-baseurlstring

![Screen Shot 2019-03-28 at 11 48 44 AM](https://user-images.githubusercontent.com/21006/55171845-793fc780-514f-11e9-870c-9fa48a264722.png)

**Comment by mfenner** [comment]
DataCite is not running a proxy doing what the last comment describes, has no code supporting this, and I also don't think it is a good idea. This sounds like a support nightmare, and it is much easier to scale DataCite infrastructure horizontally if there are bottlenecks. The MDS API used to be a an application hosted in an AWS virtual machine, since July 2018 the MDS runs as Docker containers that can be scaled up in minutes, or even automatically if the need arises.

Finally, we have started to recommend to everybody to use the JSON REST API at https://api.datacite.org instead of MDS API or EZ API for DOI registration.

**Comment by pdurbin** [comment]
@mfenner thanks! I don't have a horse in this race or a dog in this fight or whatever, but I very much appreciate the response! Thanks!
